<template>
    <q-card>
        <q-card-section>
            <div class="my-terms q-ma-lg text-weight-light text-justify" style="line-height:1.5;">
                <div class="text-subtitle1 q-mb-md q-mt-md text-weight-regular">Política de Privacidade</div>
                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">A Política de Privacidade da Playlist Software Solutions foi atualizada 15 de Janeiro de 2020.</div>
                <p>Sua privacidade é importante para a Playlist Software Solutions Então, desenvolvemos uma Política de Privacidade que abrange a forma como coletamos, usamos, divulgamos, transferimos e armazenamos suas informações. Além desta Política de Privacidade, nossos produtos também incluem informações sobre dados e privacidade para determinados recursos que solicitam o uso das suas informações pessoais. Antes de instalar e ativar os recursos, você pode analisar essas informações online, em <a href="https://playlistsolutions.com/privacy">https://playlistsolutions.com/privacy</a></p>
                <p>Dedique um momento para se familiarizar com nossas práticas de privacidade e avise-nos se tiver dúvidas, através do e-mail <a href="playlist@playlistsolutions.com">playlist@playlistsolutions.com</a> ou do telefone +55 (31) 2136 2929.</p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Coleta e uso de informações pessoais</div>
                <p>As informações pessoais registradas são dados que podem ser usados para identificar ou entrar em contato com uma única pessoa. </p>
                <p>Pode ser solicitado que você forneça suas informações pessoais no momento que realizar a ação de download de qualquer um de nossos softwares através de nossos sites <a href="https://www.playlistsolutions.com">https://www.playlistsolutions.com</a>, <a href="https://aires.studio">https://aires.studio</a>, <a href="http://airesstudio.com">http://airesstudio.com</a> e <a href="http://www.tocou.com">http://www.tocou.com</a>, ou a qualquer momento que esteja em contato com a Playlist Software Solutions. A Playlist Software Solutions pode compartilhar essas informações pessoais entre (nossos departamentos) e usá-las de modo consistente com esta Política de Privacidade. Poderemos solicitá-lo também em relação ao feedback dos produtos, do nosso atendimento e suas sugestões, as quais nos auxiliarão e podem ser utilizadas com outras informações para fornecer e melhorar nossos produtos, serviços e conteúdo. Para que possa utilizar/testar nossos produtos é necessário que nos forneça seus dados, pois não teremos como atendê-lo sem esses dados. Não é obrigatório que você forneça as informações pessoais que solicitamos, mas, caso escolha em não as fornecer, em muitos casos, não poderemos oferecer a você nossos produtos e serviços ou responder a suas dúvidas. A seguir estão alguns exemplos dos tipos de informações pessoais que a Playlist Software Solutions pode coletar e como podemos usá-los:</p>
                <ul>
                    <li>
                        <b>Quando e quais informações pessoais</b>
                        <ul>
                            <li>Quando você cria uma conta, compra um produto, baixa uma atualização de software, registra-se no serviço de suporte na Área do Cliente no site www.playlistsolutions.com, conecta-se aos nossos serviços, entra em contato conosco ou participa de uma pesquisa online, podemos coletar várias informações, incluindo seu nome, endereço de correspondência, números de telefones, endereço de e-mail, preferências de contato, identificadores do dispositivo, endereço IP, informações sobre localização e informações de cartão de crédito.</li>
                            <li>Quando você compartilha seu conteúdo com outras pessoas usando produtos Playlist Software Solutions ou convida outras pessoas para participar de serviços da Playlist Software Solutions, a Playlist Software Solutions pode coletar as informações que você fornece sobre essas pessoas, tais como nome, endereço de correspondência, endereço de e-mail e números de telefones. A Playlist Software Solutions usará essas informações para completar suas solicitações, fornecer o produto ou serviço relevante.</li>
                            <li>Em determinadas jurisdições, podemos solicitar documentos de identificação emitidos pelo governo em algumas circunstâncias, como ao configurar e ativar seu dispositivo, conforme exigido por lei.</li>
                        </ul>
                    </li>
                    <li>
                        <b>Como usamos suas informações pessoais</b>
                        <ul>
                            <li>Podemos processar suas informações pessoais para as finalidades descritas nesta Política de Privacidade com seu consentimento, para atender a obrigações legais a que a Playlist Software Solutions está sujeita ou quando avaliamos que divulgá-las é necessário de acordo com as finalidades dos interesses legítimos da Playlist Software Solutions ou de terceiros. </li>
                            <li>As informações pessoais que coletamos nos permitem manter você sempre atualizado sobre os mais recentes anúncios de produtos, atualizações de software, lançamento de novos produtos, informações de uso dos produtos e serviços e eventos promovidos pela Playlist Software Solutions. Se não quiser participar de nossa lista de distribuição, poderá optar por não recebe-las a qualquer momento atualizando suas preferências nos serviços que disponibilizamos via portais: <a href="https://www.playlistsolutions.com">https://www.playlistsolutions.com</a> e <a href="https://aires.studio">https://aires.studio</a>.</li>
                            <li>Também usamos as informações pessoais para criar, desenvolver, operar, fornecer e melhorar nossos produtos, serviços, conteúdo e publicidade, além de prevenir perdas e evitar fraudes.</li>
                            <li>Também podemos usar suas informações pessoais com finalidades relacionadas à segurança da rede e da conta, incluindo para proteger nossos serviços em benefício de todos os nossos usuários. O uso das suas informações com finalidades antifraude está condicionado à realização de transações conosco. Para finalidades antifraude, limitamos o uso dos dados ao que é estritamente necessário e de acordo com nossos legítimos interesses de  proteger nossos clientes e serviços. Em determinadas transações online, também podemos validar as informações fornecidas por você ao utilizar ferramentas comuns a serviços desta natureza.</li>
                            <li>Podemos usar suas informações pessoais, incluindo data de nascimento, para confirmar sua identidade, ajudar na identificação de usuários e determinar serviços adequados. Por exemplo, podemos usar a data de nascimento para determinar a idade de titulares de contas a serem registradas</li>
                            <li>De tempos em tempos, podemos usar suas informações pessoais para enviar avisos importantes, como comunicações sobre compras e alterações em nossos termos, condições e normas. Como essas informações são importantes para sua interação com a Playlist Software Solutions, você não pode optar por não receber as comunicações</li>
                            <li>Podemos também usar informações pessoais para propósitos internos, como: auditoria; análise de dados e pesquisas com o objetivo de melhorar os produtos e os serviços; e nas comunicações com os clientes da Playlist Software Solutions.</li>
                        </ul>
                    </li>
                </ul>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Fonte das informações pessoais não fornecidas diretamente por você</div>
                <p>Podemos receber suas informações pessoais de outras pessoas que tenham compartilhado conteúdo com você usando os produtos Playlist Software Solutions, enviado produtos ou convidado você a participar de serviços da Playlist Software Solutions. Também podemos validar com terceiros as informações fornecidas por você ao criar uma conta, a fim de garantir a segurança e evitar fraudes.</p>
                <p>Para fins de pesquisa e desenvolvimento, podemos usar conjuntos de dados que podem incluir imagens, vozes ou outros tipos de dados que podem ser associados a uma pessoa e possibilitar sua identificação. Ao capturar esses conjuntos de dados, seguimos as leis aplicáveis na jurisdição em que eles são hospedados. </p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Coleta e uso de informações não pessoais</div>
                <p>Também coletamos dados que, analisados independentemente, não permitem a associação direta a um indivíduo específico. Podemos coletar, usar, transferir e revelar informações não pessoais para qualquer propósito. A seguir estão alguns exemplos de informações não pessoais que coletamos e como podemos usá-las:</p>
                <ul>
                    <li>Podemos coletar informações como ocupação, idioma, código postal, código de área, identificador único de dispositivo, URL de referência, localização e fuso horário em que um produto Playlist Software Solutions é usado para que possamos entender melhor o comportamento do cliente e melhorar nossos produtos e serviços.</li>
                    <li>Também coletamos informações sobre atividades do cliente em fontes como nosso site, serviços Aires Cloud (em nuvens), Area do Cliente, Playlist Store -estes contidos nos endereços WEB: <a href="https://www.playlistsolutions.com">https://www.playlistsolutions.com</a>, <a href="https://aires.studio">https://aires.studio</a>, <a href="http://airesstudio.com">http://airesstudio.com</a> e <a href="http://www.tocou.com">http://www.tocou.com</a> -, Google Play e App Store, como em nossos outros produtos e serviços. Essas informações são agregadas e usadas para nos ajudar a fornecer informações mais úteis para nossos clientes e para entender quais partes de nosso site, produtos e serviços são de maior interesse. Dados agregados são considerados informações não pessoais para os propósitos desta Política de Privacidade.</li>
                    <li>Podemos coletar e armazenar detalhes sobre como você usa nossos serviços, incluindo buscas. Essas informações podem ser usadas para melhorar a relevância dos resultados oferecidos por nossos serviços. Exceto em alguns casos, para garantir a qualidade de nossos serviços pela Internet, essas informações não serão associadas a seu endereço IP.</li>
                    <li>Com seu consentimento explícito, podemos coletar dados sobre como você usa seu dispositivo e os aplicativos para ajudar os desenvolvedores de aplicativos a melhorarem seus produtos.</li>
                </ul>

                <p><i>Se nós juntarmos as informações não pessoais com informações pessoais, as informações combinadas serão tratadas como informações pessoais enquanto permanecerem combinadas.</i></p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Cookies e outras tecnologias</div>
                <p>Os sites, os serviços online, os aplicativos interativos, as mensagens por e-mail e as publicidades da Playlist Software Solutions podem usar "cookies" e outras tecnologias, como pixel tags e web beacons. Essas tecnologias nos ajudam a entender melhor o comportamento dos usuários e nos informam quais partes de nossos sites as pessoas visitaram, além de medir e contribuir para a eficácia das propagandas e pesquisas na web. Tratamos as informações coletadas por cookies e outras tecnologias como informações não pessoais. Porém, à medida que os endereços do Protocolo da Internet (IP, Internet Protocol) ou identificadores similares forem considerados informações pessoais pela lei local, também trataremos esses identificadores como informações pessoais. Similarmente, à medida que as informações não pessoais forem combinadas com informações pessoais, trataremos as informações combinadas como informações pessoais para os propósitos desta Política de Privacidade</p>
                <p>Caso não queira receber anúncios da plataforma de publicidade da Playlist Software Solutions direcionados aos seus interesses, você pode optar por não receber esses anúncios. Com isso, sua conta não receberá mais esses anúncios, seja qual for o dispositivo que você estiver usando</p>
                <p>A Playlist Software Solutions e seus parceiros também usam cookies e outras tecnologias para lembrar informações pessoais quando você usa nossos sites na web, serviços online e  aplicativos. Nossa meta nesses casos é tornar sua experiência com a Playlist Software Solutions mais conveniente e pessoal. Por exemplo, saber seu nome, nos permite dar as boasvindas a você na próxima vez que visitar um de nossos sites. Saber seu país e idioma − e se você é um técnico, locutor ou diretor − nos ajuda a fornecer uma experiência de relacionamento mais personalizada e mais útil. Saber se alguém que está usando seu computador ou dispositivo comprou um determinado produto ou usou um serviço em particular nos ajuda a tornar nossas comunicações de propaganda e por e-mail mais relevantes para seus interesses. E saber suas informações de contato, identificadores de hardware e informações sobre seu computador ou dispositivo nos ajuda a personalizar seu sistema operacional, configurar seu serviço iCloud e fornecer a você um melhor atendimento.</p>
                <p>Se você quiser desabilitar os cookies, acesse as configurações do seu navegador para gerenciar as preferências de uso de Cookies. </p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Divulgação a terceiros</div>
                <p>Eventualmente, podem ser disponibilizadas certas informações pessoais a parceiros estratégicos que trabalham com a Playlist Software Solutions para fornecer produtos e serviços que ajudam a Playlist Software Solutions na comercialização com os clientes. As informações pessoais serão somente compartilhadas pela Playlist Software Solutions para fornecer ou melhorar nossos produtos e serviços</p>

                <p><i>Essas informações pessoais não serão compartilhadas com terceiros para seus propósitos de marketing.</i></p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Centros de Serviço</div>
                <p>A Playlist Software Solutions compartilha informações pessoais com empresas que fornecem serviços, como: gestão e aprimoramento de dados de cliente, fornecimento de atendimento ao cliente, avaliação de seu interesse em nossos produtos e serviços, e condução de pesquisa do cliente ou avaliação de satisfação. Essas empresas são obrigadas a proteger suas informações e podem estar localizadas onde quer que a Playlist Software Solutions opere.</p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Outros</div>
                <p>Pode ser necessário − por lei, processo legal, litígio e/ou solicitações de autoridades públicas e governamentais dentro ou fora de seu país de residência − que a Playlist Software Solutions revele suas informações pessoais. Poderemos também revelar informações sobre você se determinarmos que, para propósitos de segurança nacional, imposição da lei ou outros problemas de importância pública, a revelação será necessária ou apropriada</p>
                <p>Também poderemos revelar informações sobre você se determinarmos que a revelação é razoavelmente necessária para impor nossos termos e condições ou proteger nossas operações ou usuários. Além disso, no caso de uma reorganização, fusão ou venda, podemos transferir qualquer e todas as informações pessoais que coletamos a terceiros relevantes.</p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Proteção de informações pessoais</div>
                <p>A Playlist Software Solutions leva a segurança de suas informações pessoais muito a sério. Os serviços online da Playlist Software Solutions, como a Area do Cliente no site da Playlist Software Solutions e o Aires Cloud, disponíveis nos portais web <a href="https://www.playlistsolutions.com">https://www.playlistsolutions.com</a>, <a href="https://aires.studio">https://aires.studio</a>, <a href="http://airesstudio.com">http://airesstudio.com</a> e <a href="http://www.tocou.com">http://www.tocou.com</a>, protegem suas informações pessoais durante a transmissão usando criptografia, como Transport Layer Security (TLS). Quando seus dados pessoais são armazenados pela Playlist Software Solutions, usamos sistemas de computação com acesso limitado e mantidos em instalações que incluem medidas físicas de segurança, mesmo quando utilizamos o armazenamento de terceiros.</p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Tomada de decisões automatizada e definição de perfis</div>
                <p>Nenhuma decisão da Playlist Software Solutions que envolve o uso de algoritmos ou a definição de perfis afeta você de maneira significativa.</p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Integridade e retenção de informações pessoais</div>
                <p>A Playlist Software Solutions permite que você mantenha facilmente suas informações pessoais precisas, completas e atualizadas. Reteremos suas informações pessoais pelo período necessário para satisfazer as finalidades descritas nesta Política de Privacidade, a menos que um período de retenção mais longo seja exigido ou permitido por lei. Para definir esses períodos, examinamos com cuidado a necessidade de coletar informações pessoais e, ao identificarmos uma necessidade relevante, retemos a informação pelo período mais curto possível necessário para concluir a finalidade da coleta, a menos que um período de retenção mais longo seja exigido por lei. </p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Acesso a informações pessoais</div>
                <p>Você pode ajudar a assegurar que suas informações e preferências de contato estejam corretas, completas e atualizadas acessando sua conta na “Área do Cliente” através do portal WEB <a href="https://www.playlistsolutions.com">https://www.playlistsolutions.com</a>. No caso de outras informações pessoais que armazenamos, ofereceremos o acesso a você e uma cópia para qualquer finalidade, incluindo solicitar que corrijamos os dados se estiverem incorretos ou que os apaguemos, contanto que a Playlist Software Solutions não seja obrigada por lei ou para fins comerciais legítimos a retêlos. Podemos recusar o processamento de solicitações que sejam infundadas/vexatórias, prejudiquem a privacidade de outros, sejam extremamente impraticáveis ou cujo acesso não seja de outra forma exigido por lei. Também podemos rejeitar determinados aspectos de solicitações para acessar ou apagar os dados se acreditarmos que isso possa comprometer o uso legítimos desses dados para os fins antifraude e de segurança descritos anteriormente. Solicitações de acesso, correção ou exclusão podem ser feitas por você por meio da “Área do Cliente” através do portal WEB <a href="https://www.playlistsolutions.com">https://www.playlistsolutions.com</a></p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Serviços de localização</div>
                <p>Para fornecer serviços de localização em produtos e serviços Playlist Software Solutions, a Playlist Software Solutions e seus parceiros podem coletar, usar e compartilhar dados de localização precisos, incluindo a localização geográfica em tempo real de seu computador ou dispositivo. Onde disponíveis, os serviços de localização poderão usar Bluetooth e seu endereço IP, além da localização de pontos de acesso Wi-Fi e torres de celular e outras tecnologias, para determinar a localização aproximada de seu dispositivo. A menos que você consinta, esses dados de localização são coletados anonimamente de forma a não identificar você pessoalmente e são usados pela Playlist Software Solutions e nossos parceiros para fornecer e melhorar produtos e serviços de localização. Por exemplo, seu dispositivo pode compartilhar sua localização geográfica com provedores de aplicativos quando você opta por usar seus serviços de localização.</p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Sites e serviços de terceiros</div>
                <p>Sites, produtos, aplicativos e serviços da Playlist Software Solutions podem conter links para sites, produtos e serviços de terceiros. Nossos produtos e serviços podem usar ou oferecer produtos ou serviços de terceiros, por exemplo, um app de terceiros para smartphone.</p>
                <p>Informações coletadas por terceiros, que podem incluir dados de localização ou informações para contato, são regidas pelas práticas de privacidade dos terceiros. </p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Usuários internacionais</div>
                <p>Todas as informações que fornecemos podem ser transferidas ou acessadas por entidades em todo o mundo, conforme descrito nesta Política de Privacidade. As informações pessoais, relacionadas a serviços Playlist Software Solutions, sobre indivíduos que residem em um estado membro do Espaço Econômico Europeu (EEE) e na Suíça são controladas pela Playlist Software Solutions e processadas em seu nome pela Playlist Software Solutions INC. A Playlist Software Solutions usa modelos aprovados de cláusulas contratuais na transferência internacional de informações pessoais coletadas no Espaço Econômico Europeu e na Suíça. A Playlist Software Solutions, na qualidade de empresa internacional, conta com duas pessoas jurídicas em jurisdições diferentes, as quais são responsáveis pelas informações pessoais que coletam e que são processadas em nome delas pela Playlist Software Solutions Inc. Por exemplo, as informações pessoais relacionadas a Playlist Software Solutions fora do Brasil são controladas por nossa entidade localizada nos Estados Unidos. </p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Nosso compromisso em toda a empresa com a sua privacidade</div>
                <p>Para estarmos certos de que suas informações pessoais estão seguras, comunicamos nossas diretrizes de privacidade e segurança aos funcionários da Playlist Software Solutions e impomos estritamente as salvaguardas de privacidade na empresa</p>

                <div class="text-subtitle2 q-mb-md q-mt-md text-weight-regular">Perguntas de privacidade</div>
                <p>Se tiver qualquer dúvida sobre a Política de Privacidade da Playlist Software Solutions ou sobre o processamento de dados, ou, ainda, se quiser fazer uma reclamação devido a uma possível violação das leis locais de privacidade, entre em contato conosco pelo correio eletrônico playlist@playlistsolutions.com ou pelo telefone +55 31 2136 2929</p>
                <p>Quando recebemos uma pergunta sobre privacidade ou informações pessoais em relação a um pedido de acesso/download, uma equipe dedicada faz a triagem dos contatos e busca atender à consulta ou preocupação específica que você levantou. Nos casos em que o problema tiver uma natureza mais significativa, mais informações suas poderão ser solicitadas. Todos os contatos significativos recebem uma resposta. Se não ficar satisfeito com a resposta que receber, você poderá encaminhar sua reclamação para o regulador relevante em sua jurisdição. Se você solicitar, nos esforçaremos para fornecer as informações sobre as opções de reclamação que podem ser aplicáveis a suas circunstâncias. </p>
                <p>A Playlist Software Solutions pode atualizar sua Política de Privacidade de tempos em tempos. Quando alterarmos a política de modo material, será postado um aviso em nossos portais WEB juntamente com a Política de Privacidade atualizada.</p>
                <p class="text-weight-bold">Playlist Soluções Ltda – CNPJ 05.869.355-0001-35 Rua Cristóvão Colombo 45 Sala 111 – Ipatinga – MG – Brasil</p>
            </div>
        </q-card-section>
    </q-card>
</template>

<script>
import { QCard, QCardSection } from 'quasar'

export default {
  name: 'PrivacyPolicy',
  data () {
    return {}
  },
  components: {
    QCard,
    QCardSection
  }
}
</script>
